"""Research-команди CLI (re-export з підмодулів)."""

from scalper_hft.cli.research_audit import (
    cmd_capacity,
    cmd_cfi,
    cmd_cohort,
    cmd_coint_scan,
    cmd_cscv,
    cmd_experiments,
    cmd_featimp,
    cmd_hedge_ratio,
    cmd_lift,
    cmd_ml,
    cmd_overfit,
    cmd_quintile,
    cmd_report,
    cmd_stress,
    cmd_survival,
    cmd_time_decay,
)
from scalper_hft.cli.research_backtest import (
    cmd_backtest,
    cmd_ml_opt,
    cmd_optimize,
    cmd_regime_backtest,
    cmd_walkforward,
)

__all__ = [
    "cmd_backtest",
    "cmd_walkforward",
    "cmd_optimize",
    "cmd_ml_opt",
    "cmd_overfit",
    "cmd_ml",
    "cmd_report",
    "cmd_cscv",
    "cmd_regime_backtest",
    "cmd_experiments",
    "cmd_cohort",
    "cmd_lift",
    "cmd_featimp",
    "cmd_cfi",
    "cmd_stress",
    "cmd_capacity",
    "cmd_survival",
    "cmd_time_decay",
    "cmd_quintile",
    "cmd_coint_scan",
    "cmd_hedge_ratio",
]
